# Generated by Django 4.0.1 on 2022-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_imagensave'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensave',
            name='format',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagensave',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img'),
        ),
    ]
