# Generated by Django 4.0.1 on 2022-02-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0003_imagensave_format_alter_imagensave_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensave',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/img/'),
        ),
    ]
